// src/components/TiltCard.jsx
import { useRef } from "react";
import {
  motion,
  useMotionValue,
  useTransform,
  useSpring,
  useMotionTemplate,
} from "framer-motion";

export default function TiltCard({ children, className = "" }) {
  const ref = useRef(null);
  const mouseX = useMotionValue(0.5);
  const mouseY = useMotionValue(0.5);

  const rotateX = useSpring(useTransform(mouseY, [0, 1], [7, -7]), {
    stiffness: 300,
    damping: 30,
  });
  const rotateY = useSpring(useTransform(mouseX, [0, 1], [-7, 7]), {
    stiffness: 300,
    damping: 30,
  });

  const shineX = useTransform(mouseX, [0, 1], [0, 100]);
  const shineY = useTransform(mouseY, [0, 1], [0, 100]);
  const shine = useMotionTemplate`radial-gradient(circle at ${shineX}% ${shineY}%, rgba(0,212,170,0.13) 0%, transparent 65%)`;

  const handleMouseMove = (e) => {
    if (!ref.current) return;
    const rect = ref.current.getBoundingClientRect();
    mouseX.set((e.clientX - rect.left) / rect.width);
    mouseY.set((e.clientY - rect.top) / rect.height);
  };

  const handleMouseLeave = () => {
    mouseX.set(0.5);
    mouseY.set(0.5);
  };

  return (
    <div style={{ perspective: "900px" }} className={className}>
      <motion.div
        ref={ref}
        style={{ rotateX, rotateY, transformStyle: "preserve-3d" }}
        onMouseMove={handleMouseMove}
        onMouseLeave={handleMouseLeave}
        className="relative h-full"
      >
        {children}
        <motion.div
          className="absolute inset-0 rounded-xl pointer-events-none z-10"
          style={{ background: shine }}
        />
      </motion.div>
    </div>
  );
}

// src/components/TiltCard.vue
<script setup>
import { ref, reactive } from 'vue'

const cardRef = ref(null)
const state = reactive({ rotateX: 0, rotateY: 0, shineX: 50, shineY: 50 })

function handleMouseMove(e) {
  if (!cardRef.value) return
  const rect = cardRef.value.getBoundingClientRect()
  const x = (e.clientX - rect.left) / rect.width
  const y = (e.clientY - rect.top) / rect.height
  state.rotateX = (y - 0.5) * -14
  state.rotateY = (x - 0.5) * 14
  state.shineX = x * 100
  state.shineY = y * 100
}

function handleMouseLeave() {
  state.rotateX = 0
  state.rotateY = 0
  state.shineX = 50
  state.shineY = 50
}
</script>

<template>
  <div style="perspective: 900px">
    <div
      ref="cardRef"
      class="relative h-full"
      :style="{
        transformStyle: 'preserve-3d',
        transform: `rotateX(${state.rotateX}deg) rotateY(${state.rotateY}deg)`,
        transition: 'transform 0.18s cubic-bezier(0.16, 1, 0.3, 1)',
      }"
      @mousemove="handleMouseMove"
      @mouseleave="handleMouseLeave"
    >
      <slot />
      <div
        class="absolute inset-0 rounded-xl pointer-events-none z-10"
        :style="{
          background: `radial-gradient(circle at ${state.shineX}% ${state.shineY}%, rgba(0,212,170,0.13) 0%, transparent 65%)`,
        }"
      />
    </div>
  </div>
</template>
